# Generated by Django 2.1.3 on 2018-12-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0002_auto_20181229_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
